Repository SKemenov/iOS-FakeNFT-T5, pull requests merged in 2024-01, with the labels that each got.

#65 Catalog3-3
  FakeNFT.xcodeproj/project.pbxproj
  FakeNFT/AppDelegate.swift
  FakeNFT/DesignSystem/Colors.swift
  FakeNFT/Foundation/CellsReusingUtils.swift
  FakeNFT/Foundation/MemoryStorage/NftStorage.swift
  FakeNFT/Foundation/MemoryStorage/NftStorageTest.swift
  FakeNFT/Foundation/MemoryStorage/ProfileStorage.swift
  FakeNFT/Foundation/NetworkClient/NetworkClient.swift
  FakeNFT/Foundation/NetworkClient/NetworkRequest.swift
  FakeNFT/Foundation/NetworkClient/NetworkTask.swift
  FakeNFT/Foundation/UIView+Constraints.swift
  FakeNFT/Models/CollectionsModel.swift
  FakeNFT/Models/CollectionsResult.swift
  FakeNFT/Models/Order.swift
  FakeNFT/Models/ProfileModel.swift
  FakeNFT/Models/ProfileResult.swift
  FakeNFT/Models/ProfileUpdate.swift
  FakeNFT/SceneDelegate.swift
  FakeNFT/Scenes /Catalog/CatalogCell.swift
  FakeNFT/Scenes /Catalog/CatalogViewController.swift
  FakeNFT/Scenes /Catalog/CollectionCell.swift
  FakeNFT/Scenes /Catalog/CollectionViewController.swift
  FakeNFT/Scenes /Catalog/TestCatalogController.swift
  FakeNFT/Scenes /TabBarController/TabBarController.swift
  FakeNFT/Scenes /WebView/WebViewViewController.swift
  FakeNFT/Services/CollectionsService.swift
  FakeNFT/Services/NftService.swift
  FakeNFT/Services/OrderService.swift
  FakeNFT/Services/ProfileService.swift
  FakeNFT/Services/Requests/CollectionsRequest.swift
  FakeNFT/Services/Requests/NftByIdRequest.swift
  FakeNFT/Services/Requests/NftRequest.swift
  FakeNFT/Services/Requests/OrderRequest.swift
  FakeNFT/Services/Requests/ProfileRequests.swift
  FakeNFT/Services/Requests/RequestConstants.swift
  FakeNFT/Services/ServicesAssemly.swift
  FakeNFT/Services/UIBlockingProgressHUD.swift
  FakeNFT/UserDefaultsManager/UserDefaultsManager.swift
  docs/N5CatalogDecomposition.md
Labels: Логика

#66 Profile 3/3
  FakeNFT/Scenes /Profile/FavoritesNft/FavoriteNftsCollectionViewCell.swift
  FakeNFT/Scenes /Profile/FavoritesNft/FavoriteNftsViewController.swift
  FakeNFT/Scenes /Profile/MyNft/MyNftTableViewCell.swift
  FakeNFT/Scenes /Profile/MyNft/MyNftViewController.swift
  FakeNFT/Scenes /Profile/ProfileViewController.swift
  docs/ProfileDecomposition.md
Labels: Логика, Код ревью

#67 Statistics 2-3 PR
  FakeNFT.xcodeproj/project.pbxproj
  FakeNFT/Foundation/MemoryStorage/NftStorage.swift
  FakeNFT/Foundation/NetworkClient/NetworkClient.swift
  FakeNFT/Foundation/NetworkClient/NetworkRequest.swift
  FakeNFT/Models/Network/Nft.swift
  FakeNFT/Models/UserModel.swift
  FakeNFT/Resources/Statistics.swift
  FakeNFT/Scenes /NftDetails/NftDetailPresenter.swift
  FakeNFT/Scenes /Statistics/Extensions/CGFloat+Extensions.swift
  FakeNFT/Scenes /Statistics/Extensions/UIImageView+extensions.swift
  FakeNFT/Scenes /Statistics/Extensions/UserDefaults+Extension.swift
  FakeNFT/Scenes /Statistics/StatisticsViewController.swift
  FakeNFT/Scenes /Statistics/UserDetails/Collection/CollectionCell.swift
  FakeNFT/Scenes /Statistics/UserDetails/Collection/CollectionViewController.swift
  FakeNFT/Scenes /Statistics/UserDetails/UserCell.swift
  FakeNFT/Scenes /Statistics/UserDetails/UserDetailsViewController.swift
  FakeNFT/Scenes /Statistics/UserDetails/WebViewViewController.swift
  FakeNFT/Scenes /TabBarController/TabBarController.swift
  FakeNFT/Services/NftServiceProtocol.swift
  FakeNFT/Services/Requests/ProfileRequest.swift
  FakeNFT/Services/Requests/RequestConstants.swift
  FakeNFT/Services/Requests/UsersRequest.swift
  FakeNFT/Services/ServicesAssemly.swift
  FakeNFT/Services/UIBlockingProgressHUD.swift
  FakeNFT/Services/UsersService.swift
  docs/StatisticsDecomposition.md
Labels: Код ревью
